from __future__ import annotations

import os


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


ENABLE_EMBED_FAST_MATCH = _env_bool("ENABLE_EMBED_FAST_MATCH", True)
ENABLE_FAST_STRING_MATCH = _env_bool("ENABLE_FAST_STRING_MATCH", True)
ENABLE_LLM = _env_bool("ENABLE_LLM", True)
NOT_ALLOWED_LLM_RERANK_ENABLED = _env_bool("NOT_ALLOWED_LLM_RERANK_ENABLED", True)
NOT_ALLOWED_LLM_RERANK_THINK = os.getenv("NOT_ALLOWED_LLM_RERANK_THINK", "false").strip().lower() in {"1", "true", "yes", "on"}

FAST_NAME_STRONG_THRESHOLD = float(os.getenv("FAST_NAME_STRONG_THRESHOLD", "0.93"))
FAST_NAME_BORDERLINE_THRESHOLD = float(os.getenv("FAST_NAME_BORDERLINE_THRESHOLD", "0.88"))
FAST_DESC_STRONG_THRESHOLD = float(os.getenv("FAST_DESC_STRONG_THRESHOLD", "0.90"))
FAST_DESC_BORDERLINE_THRESHOLD = float(os.getenv("FAST_DESC_BORDERLINE_THRESHOLD", "0.84"))
FAST_TOKEN_COVERAGE_THRESHOLD = float(os.getenv("FAST_TOKEN_COVERAGE_THRESHOLD", "0.60"))
FAST_DESC_TOKEN_COVERAGE_THRESHOLD = float(os.getenv("FAST_DESC_TOKEN_COVERAGE_THRESHOLD", "0.50"))
FAST_MIN_TOKEN_OVERLAP = int(os.getenv("FAST_MIN_TOKEN_OVERLAP", "2"))
FAST_SCORE_MARGIN_THRESHOLD = float(os.getenv("FAST_SCORE_MARGIN_THRESHOLD", "0.035"))
FAST_ZONE_CANDIDATE_MIN_THRESHOLD = float(os.getenv("FAST_ZONE_CANDIDATE_MIN_THRESHOLD", "0.46"))
FAST_ZONE_NAME_STRONG_THRESHOLD = float(os.getenv("FAST_ZONE_NAME_STRONG_THRESHOLD", "0.91"))
FAST_ZONE_NAME_BORDERLINE_THRESHOLD = float(os.getenv("FAST_ZONE_NAME_BORDERLINE_THRESHOLD", "0.86"))
FAST_ZONE_SUMMARY_STRONG_THRESHOLD = float(os.getenv("FAST_ZONE_SUMMARY_STRONG_THRESHOLD", "0.88"))
FAST_ZONE_SUMMARY_BORDERLINE_THRESHOLD = float(os.getenv("FAST_ZONE_SUMMARY_BORDERLINE_THRESHOLD", "0.82"))

LOCAL_EMBED_STRONG_THRESHOLD = float(os.getenv("LOCAL_EMBED_STRONG_THRESHOLD", "0.82"))
LOCAL_EMBED_BORDERLINE_THRESHOLD = float(os.getenv("LOCAL_EMBED_BORDERLINE_THRESHOLD", "0.72"))
LOCAL_EMBED_MARGIN_THRESHOLD = float(os.getenv("LOCAL_EMBED_MARGIN_THRESHOLD", "0.035"))

NOT_ALLOWED_CANDIDATES_TOP_N = int(os.getenv("NOT_ALLOWED_CANDIDATES_TOP_N", "5"))
NOT_ALLOWED_LLM_RERANK_RECALL_TOP_N = int(os.getenv("NOT_ALLOWED_LLM_RERANK_RECALL_TOP_N", "20"))
NOT_ALLOWED_CANDIDATES_MIN_SIMILARITY = float(os.getenv("NOT_ALLOWED_CANDIDATES_MIN_SIMILARITY", "0.0"))
NOT_ALLOWED_LLM_RERANK_DESC_MAX_CHARS = int(os.getenv("NOT_ALLOWED_LLM_RERANK_DESC_MAX_CHARS", "480"))
TOP_N_EMBED_CANDIDATES = int(os.getenv("TOP_N_EMBED_CANDIDATES", "5"))
TOP_N_EMBED_CANDIDATES_HARD = int(os.getenv("TOP_N_EMBED_CANDIDATES_HARD", "8"))
MIN_EMBED_CANDIDATE_SIMILARITY = float(os.getenv("MIN_EMBED_CANDIDATE_SIMILARITY", "0.52"))
MAX_EMBED_CANDIDATES_IN_PROMPT = int(os.getenv("MAX_EMBED_CANDIDATES_IN_PROMPT", "8"))
NOT_ALLOWED_LLM_RERANK_MAX_ATTEMPTS = int(os.getenv("NOT_ALLOWED_LLM_RERANK_MAX_ATTEMPTS", "3"))
NOT_ALLOWED_LLM_RERANK_RETRY_DELAY_SEC = float(os.getenv("NOT_ALLOWED_LLM_RERANK_RETRY_DELAY_SEC", "0.35"))

FAST_DESC_MAX_TOKENS = int(os.getenv("FAST_DESC_MAX_TOKENS", "24"))
DIRECT_DESC_MAX_TOKENS = int(os.getenv("DIRECT_DESC_MAX_TOKENS", "48"))
DIRECT_DESC_COVERAGE_THRESHOLD = float(os.getenv("DIRECT_DESC_COVERAGE_THRESHOLD", "0.85"))
DIRECT_DESC_SEQ_THRESHOLD = float(os.getenv("DIRECT_DESC_SEQ_THRESHOLD", "0.84"))
DIRECT_DESC_MIN_OVERLAP = int(os.getenv("DIRECT_DESC_MIN_OVERLAP", "2"))

GLOBAL_TFIDF_WEIGHT = float(os.getenv("GLOBAL_TFIDF_WEIGHT", "2.0"))
GLOBAL_EXACT_MAIN_BONUS = float(os.getenv("GLOBAL_EXACT_MAIN_BONUS", "4.0"))
GLOBAL_EXACT_CONDITIONAL_BONUS = float(os.getenv("GLOBAL_EXACT_CONDITIONAL_BONUS", "3.0"))
GLOBAL_EXACT_AUXILIARY_BONUS = float(os.getenv("GLOBAL_EXACT_AUXILIARY_BONUS", "2.0"))
INTERSECT_ZONE_PRIOR_BONUS = float(os.getenv("INTERSECT_ZONE_PRIOR_BONUS", "0.5"))
DOMINANT_PZZ_MIN_SHARE = float(os.getenv("DOMINANT_PZZ_MIN_SHARE", "0.5"))

LLM_LONG_TEXT_HARD_CASE_MIN_LEN = int(os.getenv("LLM_LONG_TEXT_HARD_CASE_MIN_LEN", "70"))
ENABLE_PROFILED_FAST_MATCH = _env_bool("ENABLE_PROFILED_FAST_MATCH", True)
ALLOW_ZONE_NAME_SUMMARY_AUTOMATCH = _env_bool("ALLOW_ZONE_NAME_SUMMARY_AUTOMATCH", False)
RESIDENTIAL_AUTO_REQUIRES_SUBTYPE = _env_bool("RESIDENTIAL_AUTO_REQUIRES_SUBTYPE", True)
PROFILED_EMBED_RESTRICTION = _env_bool("PROFILED_EMBED_RESTRICTION", True)
LLM_BACKEND = os.getenv("LLM_BACKEND", "vllm")
LLM_MODEL = os.getenv("LLM_MODEL", os.getenv("GENERATE_MODEL", "openai/gpt-oss-20b" if LLM_BACKEND == "vllm" else "gpt-oss:20b"))
